// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import Pengumuman from './Pengumuman';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	ImageCards,
	Pengumuman,
	Quote,
	Text,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	pengumuman: Pengumuman,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
};
